Practica
========================================================
Clase: Reading Local Files 05/2014
========================================================

Curso: "Getting and Cleaning Data"
========================================================
Programa de Análisis de Datos de la John Hopkins en Coursera
========================================================

Esta clase supone que de la anterior (downloading files) se logró el objetivo de descargar los datos de las cámaras de fotomultas de la ciudad de Baltimore.

Durante la lectura, se hará énfasis en como "leer" datos proveninetes de archivos "planos".

Retomando la descarga de datos
-------------------------

```{r}
if (!file.exists("data")){
        dir.create("data")
}
#Si el directorio "data" no existía, se ha creado
if (!file.exists("data/cameras.csv")){
        FileUrl <- "https://data.baltimorecity.gov/api/views/dz54-2aru/rows.csv?accessType=DOWNLOAD" #Llena la variable con la URL de descarga
download.file(url=FileUrl,destfile="./data/cameras.csv") #Descarga los datos (el fichero)
}
#Si el archivo "cameras.csv" no existe, lo descarga
# ,method="curl" debe agregarse en algunos OS
````


Funcion Principal
-------------------------

La función principal para cargar (leer) datos en R es read.table() en tanto con ella se puede hacer carga de manera flexible y robusta. Sin embargo, requiere varios parametros y utiliza la RAM (muchos datos, pueden saturarla y/o causar problemas).

Sus parámetros principales son:
file (el archivo)
header (contiene encabezado?)
sep (el tipo de separador de datos) row.names (el nombre de las filas, si aplica)
nrow (número de filas)

```
cameraData <- read.table(file="./data/cameras.csv", sep=",", header=TRUE)
head(cameraData)
                        address direction      street  crossStreet
1       S CATON AVE & BENSON AVE       N/B   Caton Ave   Benson Ave
2       S CATON AVE & BENSON AVE       S/B   Caton Ave   Benson Ave
3 WILKENS AVE & PINE HEIGHTS AVE       E/B Wilkens Ave Pine Heights
4        THE ALAMEDA & E 33RD ST       S/B The Alameda      33rd St
5        E 33RD ST & THE ALAMEDA       E/B      E 33rd  The Alameda
6        ERDMAN AVE & N MACON ST       E/B      Erdman     Macon St
                intersection                      Location.1
1     Caton Ave & Benson Ave (39.2693779962, -76.6688185297)
2     Caton Ave & Benson Ave (39.2693157898, -76.6689698176)
3 Wilkens Ave & Pine Heights  (39.2720252302, -76.676960806)
4     The Alameda  & 33rd St (39.3285013141, -76.5953545714)
5      E 33rd  & The Alameda (39.3283410623, -76.5953594625)
6         Erdman  & Macon St (39.3068045671, -76.5593167803)
```
Una opción para los archivos planos tipo CSV, es usar la función read.csv() con ella se tiene de manera automática que sep= "," y header= TRUE

Parametros destacados en lectura de datos
-------------------------

### quote (quote= )

Se utiliza para explicitar el contenido "citado" (usando comilla simple o compuesta)

### na.strings (na.strings= )

Establece el caracter que simboliza los missing values (NA's)

### nrows (nrow= )

Indica el número de filas que serán leida del archivo, luego, no solo sirve para indicar el límite del contenido, sino para limitar su lectura.

### skip (skip= )

Indica el número de filas a saltarse antes de empezar a cargar contenido


